# Generated by Django 6.0 on 2025-12-15 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_user_phone_number_alter_user_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='phone_number',
        ),
    ]
