# Generated by Django 6.0 on 2025-12-17 09:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_income'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='time',
            field=models.TimeField(blank=True, default=datetime.time(0, 0)),
        ),
        migrations.AlterField(
            model_name='income',
            name='time',
            field=models.TimeField(blank=True, default=datetime.time(0, 0)),
        ),
    ]
