# Generated by Django 6.0 on 2025-12-18 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_alter_expense_time_alter_income_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='updated_time',
            field=models.TimeField(auto_now=True),
        ),
    ]
