# Generated by Django 6.0 on 2025-12-18 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_expense_updated_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='updated_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='updated_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
