# Generated by Django 6.0 on 2025-12-18 14:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_income_updated_time_alter_expense_updated_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='time',
            field=models.TimeField(blank=True, default=datetime.time(17, 38, 4, 678607)),
        ),
        migrations.AlterField(
            model_name='income',
            name='time',
            field=models.TimeField(blank=True, default=datetime.time(17, 38, 4, 678948)),
        ),
    ]
