# Generated by Django 6.0 on 2025-12-18 14:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_alter_expense_time_alter_income_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='time',
            field=models.TimeField(default=datetime.time(17, 46, 55, 901808)),
        ),
        migrations.AlterField(
            model_name='income',
            name='time',
            field=models.TimeField(blank=True, default=datetime.time(17, 46, 55, 902120)),
        ),
    ]
