# Generated by Django 6.0 on 2025-12-18 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_alter_expense_time_alter_income_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='time',
            field=models.TimeField(blank=True),
        ),
    ]
