# Generated by Django 6.0 on 2025-12-18 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0014_alter_income_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='updated_time',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='income',
            name='updated_time',
            field=models.DateField(auto_now=True),
        ),
    ]
