# Generated by Django 6.0 on 2025-12-18 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0016_alter_expense_date_alter_income_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='income',
            name='date',
            field=models.DateField(blank=True),
        ),
    ]
