# Generated by Django 6.0 on 2025-12-25 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0018_alter_user_first_name_alter_user_last_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="expense",
            name="jdate",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="income",
            name="jdate",
            field=models.CharField(blank=True, null=True),
        ),
    ]
